# Generated by Django 5.2.2 on 2025-06-11 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('vat', models.DecimalField(decimal_places=2, help_text='Процент НДС, например 20.00', max_digits=5, verbose_name='НДС (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование заезда')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=10, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала заезда')),
                ('end_date', models.DateField(verbose_name='Дата окончания заезда')),
                ('application_start', models.DateTimeField(verbose_name='Дата и время начала подачи заявки')),
                ('application_end', models.DateTimeField(verbose_name='Дата и время окончания подачи заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rate', verbose_name='Тариф для заезда')),
            ],
        ),
    ]
