# Generated by Django 5.2.2 on 2025-07-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='room_layout',
        ),
    ]
