# Generated by Django 5.2.2 on 2025-07-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_rate_room_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='guests_placemented',
            field=models.BooleanField(default=False, verbose_name='Все гости размещены'),
        ),
    ]
