# Generated by Django 5.2.2 on 2025-06-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rate_arrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование номера')),
                ('capacity', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('building_type', models.CharField(max_length=100, verbose_name='Тип корпуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='building_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип корпуса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='rate',
            name='room_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.roomlayout', verbose_name='Планировка номера'),
        ),
    ]
