# Generated by Django 5.2.2 on 2025-06-12 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roomlayout_rate_building_type_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Суперадмин'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('guests', models.TextField(verbose_name='Список отдыхающих')),
                ('rooms', models.TextField(blank=True, null=True, verbose_name='Комнаты отдыхающих')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('sent', 'Отправлена'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачена'), ('pending', 'Ожидает оплаты'), ('paid', 'Оплачена')], default='unpaid', max_length=20, verbose_name='Статус оплаты')),
                ('document', models.FileField(blank=True, null=True, upload_to='applications/docs/', verbose_name='Прикрепленный документ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки заявки')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.arrival', verbose_name='Связанный заезд')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
            ],
        ),
    ]
