# Generated by Django 5.2.2 on 2025-06-12 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='quota',
            field=models.PositiveIntegerField(default=3, verbose_name='Количество квот'),
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('relation', models.CharField(max_length=50, verbose_name='Родственные отношения')),
                ('is_employee_child', models.BooleanField(default=False, verbose_name='Является ребенком сотрудника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='relatives',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.relative'),
        ),
    ]
