# Generated by Django 5.2.2 on 2025-06-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_birthdate_user_patronymic_user_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('sent', 'Отправлена'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена'), ('revision', 'На доработке')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
