# Generated by Django 5.2.2 on 2025-07-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_application_comment_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_fio', models.CharField(max_length=200, verbose_name='ФИО гостя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='core.application')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_placements', to='core.arrival')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='core.roomlayout')),
            ],
        ),
    ]
